import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import { site } from "@/lib/site";
import { getPublicSettings } from "@/lib/settings";
import { getPublishedTheme } from "@/lib/theme-settings";
import { ALL_FONT_VARIABLES } from "@/lib/fonts";
import { ThemeVars } from "@/components/theme/theme-vars";
import { Providers } from "@/components/providers";
import { themeInitScript } from "@/lib/theme";
import "./globals.css";

/**
 * Site metadata, with the default title, description and social image read from
 * the admin SEO settings. `getPublicSettings` is tag-cached and falls back to
 * the previously hard-coded copy, so this stays a static read — it introduces no
 * per-request work and no dynamic rendering.
 */
export async function generateMetadata(): Promise<Metadata> {
  const settings = await getPublicSettings();

  return {
    metadataBase: new URL(site.url),
    title: {
      default: settings.seoDefaultTitle,
      template: `%s | ${settings.storeName}`,
    },
    description: settings.seoDefaultDescription,
    alternates: { canonical: "/" },
    openGraph: {
      type: "website",
      locale: "tr_TR",
      url: site.url,
      siteName: settings.storeName,
      title: settings.seoDefaultTitle,
      description: settings.seoDefaultDescription,
      images: [
        {
          url: settings.seoSocialImage,
          width: 1536,
          height: 2040,
          alt: "Kurumaya serilmiş kabuklu Kabia bademleri",
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: settings.seoDefaultTitle,
      description: settings.seoDefaultDescription,
      images: [settings.seoSocialImage],
    },
    robots: { index: true, follow: true },
  };
}

export const viewport: Viewport = {
  themeColor: "#f4f1e8",
};

/** Organization data limited to facts from the existing Kabia project. */
const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: site.name,
  url: site.url,
  logo: `${site.url}/images/logo.svg`,
  email: site.email,
  telephone: site.phone,
  address: {
    "@type": "PostalAddress",
    addressLocality: "Geyve",
    addressRegion: "Sakarya",
    postalCode: "54700",
    streetAddress: "Sabırlar",
    addressCountry: "TR",
  },
  sameAs: [site.social.instagram, site.social.facebook, site.social.x],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getPublishedTheme();

  // SEC-09: Read the per-request nonce generated by the proxy for CSP.
  // This is used on inline scripts (theme init + JSON-LD) so they pass
  // the nonce-based CSP without 'unsafe-inline'.
  const h = await headers();
  const nonce = h.get("x-nonce") ?? undefined;

  return (
    <html
      lang="tr"
      className={`${ALL_FONT_VARIABLES} h-full`}
      suppressHydrationWarning
    >
      <head>
        {/* Applies the stored light/dark choice before first paint. */}
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} nonce={nonce} />
        {/* Applies the published theme variables before first paint. */}
        <ThemeVars theme={theme} />
      </head>
      <body className="min-h-full flex flex-col">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
          nonce={nonce}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
